### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by XiaoZhang-NN** [pangshumao/SpineParseNet#1]
您好，按照您的数据文件夹排列各个文件夹，一直报错：我已经把文件夹换成我自己的文件夹，并把gz数据放到最后的mr和mask文件夹里了。
step 1: create the h5 dataset for coarse segmentation stage....................................................................
Traceback (most recent call last):
  File "./datasets/coarse_create_h5.py", line 74, in <module>
    val_ind=val_ind, test_ind=test_ind)
  File "<__array_function__ internals>", line 6, in savez
  File "/home/zhangxiao/anaconda3/envs/qiuqiu_fde/lib/python3.7/site-packages/numpy/lib/npyio.py", line 617, in savez
    _savez(file, args, kwds, False)
  File "/home/zhangxiao/anaconda3/envs/qiuqiu_fde/lib/python3.7/site-packages/numpy/lib/npyio.py", line 713, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/zhangxiao/anaconda3/envs/qiuqiu_fde/lib/python3.7/site-packages/numpy/lib/npyio.py", line 112, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/home/zhangxiao/anaconda3/envs/qiuqiu_fde/lib/python3.7/zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/public/data/coarse/split_ind_fold1.npz'
step 2: training the DeepLabv3+ model for coarse segmentation stage............................................................

**Comment by pangshumao** [comment]
你好，main.sh第2行data_root_dir=/public/data得改为你的数据根目录，有问题可以在比赛qq群（854917214）里沟通。
















在 2021-04-22 19:55:05，"XiaoZhang-NN" ***@***.***> 写道：

您好，按照您的数据文件夹排列各个文件夹，一直报错：我已经把文件夹换成我自己的文件夹，并把gz数据放到最后的mr和mask文件夹里了。
step 1: create the h5 dataset for coarse segmentation stage....................................................................
Traceback (most recent call last):
File "./datasets/coarse_create_h5.py", line 74, in
val_ind=val_ind, test_ind=test_ind)
File "<array_function internals>", line 6, in savez
File "/home/zhangxiao/anaconda3/envs/qiuqiu_fde/lib/python3.7/site-packages/numpy/lib/npyio.py", line 617, in savez
_savez(file, args, kwds, False)
File "/home/zhangxiao/anaconda3/envs/qiuqiu_fde/lib/python3.7/site-packages/numpy/lib/npyio.py", line 713, in _savez
zipf = zipfile_factory(file, mode="w", compression=compression)
File "/home/zhangxiao/anaconda3/envs/qiuqiu_fde/lib/python3.7/site-packages/numpy/lib/npyio.py", line 112, in zipfile_factory
return zipfile.ZipFile(file, *args, **kwargs)
File "/home/zhangxiao/anaconda3/envs/qiuqiu_fde/lib/python3.7/zipfile.py", line 1240, in init
self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/public/data/coarse/split_ind_fold1.npz'
step 2: training the DeepLabv3+ model for coarse segmentation stage............................................................
